version: "3.8"
services:
  backend:
    container_name: api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./server:/app
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_URL: '/be'
    restart: always
  nginx:
    container_name: nginx
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"